version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - django_app
    networks:
      - notes-app-nw

  django_app:
    build:
      context: .
    image: django_app
    container_name: "django_cont"
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    env_file:
      - ".env"
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - notes-app-nw

  db:
    image: mysql
    container_name: "db_cont"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
    volumes:
      - ./data/mysql/db:/var/lib/mysql_data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - notes-app-nw

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports: 
     - "3100:3100"
    volumes:
     -  ${PWD}:/mnt/config
     -  ${PWD}/data/loki:/var/lib/loki_data
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
     - notes-app-nw 
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
    networks:
      - notes-app-nw  
    restart: always
    volumes:
      - ./data/grafana:/var/lib/grafana
  
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ${PWD}:/mnt/config
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/mnt/config/promtail-config.yaml
    ports:
      - "6000:6000"
    depends_on:
      - loki
    networks:
      - notes-app-nw    

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "5090:8080"
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - notes-app-nw
    restart: always

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    networks:
      - notes-app-nw
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "0"
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/data/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - notes-app-nw
    depends_on:
      - node_exporter
      - cadvisor
    restart: unless-stopped

networks:
  notes-app-nw:

volumes:
  mysql_data:
  loki_data:
  prometheus_data:
  grafana:

 
